// ===== AI TV MARKETPLACE DATA =====

const CATEGORIES = [
  { id: 'ai-fundamentals', name: 'Workshops',                  emoji: '🧠', color: '#7B88FB', bg: '#eef0ff', count: 5 },
  { id: 'programming',     name: 'Bonuses',                    emoji: '💰', color: '#272659', bg: '#e8e8f5', count: 44 },
  { id: 'creative',        name: 'Masterclass',                emoji: '🎓', color: '#CDB5FB', bg: '#f5f0ff', count: 29 },
  { id: 'kids',            name: 'Personal Training',          emoji: '🏋️', color: '#22c55e', bg: '#f0fdf4', count: 22 },
  { id: 'business',        name: 'Growth Wealth Masterclass',  emoji: '📈', color: '#f59e0b', bg: '#fffbeb', count: 31 },
  { id: 'advanced',        name: 'Advanced AI',                emoji: '🚀', color: '#ef4444', bg: '#fef2f2', count: 27 },
];

const SUBCATEGORIES = {
  'ai-fundamentals': ['All', 'Python', 'Tech Skills', 'AI Tools', 'Excel', 'Stock Market'],
  'programming':     ['All', 'Python for AI', 'JavaScript AI', 'AI APIs', 'Build Chatbots', 'AI Tools'],
  'creative':        ['All', 'AI Art', 'AI Music', 'AI Video', 'AI Writing', 'Image Generation'],
  'kids':            ['All', 'Scratch + AI', 'Fun Robots', 'AI Games', 'AI Stories', 'Young Coders'],
  'business':        ['All', 'AI Marketing', 'AI Productivity', 'AI for Teams', 'AI Strategy', 'Automation'],
  'advanced':        ['All', 'Deep Learning', 'Computer Vision', 'NLP', 'Reinforcement Learning', 'MLOps'],
};

const COURSES = [
  // Workshops (ai-fundamentals)
  { id: 1,  title: 'Python using AI Workshop',        category: 'ai-fundamentals', subcategory: 'Python',        emoji: '🐍', bg: '#eef0ff', price: 199,  originalPrice: 1999,  rating: 4.9, reviews: 3241, level: 'beginner',     duration: '3h',     lessons: 18, instructor: 'Aditya Kachave & Aman Saurav',   badge: 'Bestseller', includes: ['3 hours of live workshop recording','Python cheat sheet','Certificate of completion','Lifetime access','Community support'], desc: 'Learn Python the smart way — using AI as your coding assistant! In this hands-on workshop, Aditya Kachave and Aman Saurav walk you through Python fundamentals with AI tools that accelerate your learning 10x.', curriculum: ['Setting Up Python with AI Help','Variables & Logic with Copilot','Functions & Loops','Working with Files','AI-Assisted Debugging','Building Mini Projects','Automating Tasks','Your AI-Powered Python Journey'] },
  { id: 2,  title: '10X Techie using AI Workshop',   category: 'ai-fundamentals', subcategory: 'Tech Skills',   emoji: '⚡', bg: '#f0f4ff', price: 9,    originalPrice: 999,   rating: 4.8, reviews: 5102, level: 'beginner',     duration: '2h',     lessons: 12, instructor: 'Prakhar Bafna & Aman Saurav',    badge: 'Hot Deal',   includes: ['2 hours of workshop video','AI tools guide','Resource kit','Certificate','Telegram community'], desc: 'Become a 10X more productive techie using the latest AI tools! Prakhar Bafna and Aman Saurav share their proven system to supercharge your skills, automate routine work, and stand out in the tech world.', curriculum: ['The 10X Techie Mindset','Top AI Tools for Developers','AI-Powered Code Review','Speed Up with ChatGPT & Claude','Building Smarter, Not Harder','AI for Documentation','Productivity Workflows','Your 10X Action Plan'] },
  { id: 3,  title: 'AI Tools Workshop',              category: 'ai-fundamentals', subcategory: 'AI Tools',      emoji: '🛠️', bg: '#f5f0ff', price: 9,    originalPrice: 999,   rating: 4.9, reviews: 4876, level: 'beginner',     duration: '2h 30m', lessons: 14, instructor: 'Aditya Kachave & Aditya Goenka', badge: 'Hot Deal',   includes: ['2.5 hours of workshop video','AI tools cheat sheet','Certificate','Lifetime access'], desc: 'Master the most essential AI tools in one power-packed workshop! Aditya Kachave and Aditya Goenka take you through the best AI tools for productivity, creativity, and career growth — all in one session.', curriculum: ['AI Tools Landscape 2026','ChatGPT Mastery','Claude & Gemini','AI for Design (Midjourney)','AI for Content Creation','AI for Research','Workflow Automation','Building Your Personal AI Stack'] },
  { id: 4,  title: 'Excel using AI',                category: 'ai-fundamentals', subcategory: 'Excel',         emoji: '📊', bg: '#fff8ee', price: 99,   originalPrice: 999,   rating: 4.8, reviews: 2987, level: 'beginner',     duration: '2h',     lessons: 10, instructor: 'Aditya Goenka',                 badge: 'Popular',    includes: ['2 hours of workshop video','Excel AI templates','Formula cheat sheet','Certificate'], desc: 'Transform the way you use Excel with the power of AI! Aditya Goenka shows you how to use AI to write formulas, analyse data, build dashboards, and automate reporting — no prior Excel expertise needed.', curriculum: ['Excel + AI Basics','Generating Formulas with AI','Data Cleaning Automation','AI-Powered Pivot Tables','Smart Charts & Dashboards','Conditional Formatting with AI','Automating Reports','Excel AI Templates You Can Use Now'] },
  { id: 5,  title: 'Stock Market using AI',         category: 'ai-fundamentals', subcategory: 'Stock Market',  emoji: '📈', bg: '#f0fff4', price: 9,    originalPrice: 999,   rating: 4.7, reviews: 3654, level: 'beginner',     duration: '2h 30m', lessons: 14, instructor: 'PRATIK CHAKRABORTY & Rahul Chandra', badge: 'Hot Deal', includes: ['2.5 hours of workshop video','Market analysis templates','AI tools guide','Certificate'], desc: 'Decode the stock market using AI! PRATIK CHAKRABORTY and Rahul Chandra teach you how to use AI tools for stock research, trend analysis, and smarter investment decisions — even as a complete beginner.', curriculum: ['Stock Market Fundamentals','How AI Reads Markets','AI Tools for Stock Research','Sentiment Analysis with AI','Technical Analysis + AI','Building a Watchlist with AI','Risk Management Strategies','Your First AI-Assisted Trade Plan'] },

  // Programming
  { id: 6,  title: 'Python for AI — Zero to Hero',   category: 'programming',     subcategory: 'Python for AI',     emoji: '🐍', bg: '#e8f5e9', price: 1699,  originalPrice: 4599,  rating: 4.9, reviews: 7823, level: 'beginner',     duration: '12h',    lessons: 88, instructor: 'Leo Martinez',    badge: 'Bestseller', includes: ['12 hours of video','50+ exercises','Project files','Certificate','Office hours'], desc: 'Go from zero Python knowledge to building real AI projects. This comprehensive course covers Python fundamentals, data manipulation, and popular AI libraries.', curriculum: ['Python Basics','Variables & Data Types','Loops & Functions','Lists & Dictionaries','File Handling','Intro to NumPy','Pandas for Data','Building Your First AI Script'] },
  { id: 7,  title: 'Build Your First Chatbot',       category: 'programming',     subcategory: 'Build Chatbots',    emoji: '🤖', bg: '#e3f2fd', price: 2099,  originalPrice: 5499,  rating: 4.8, reviews: 3912, level: 'intermediate', duration: '7h',     lessons: 52, instructor: 'Priya Sharma',    badge: 'Popular',    includes: ['7 hours of video','Source code','API keys guide','Certificate'], desc: 'Build a fully functional AI chatbot from scratch! Learn to use modern AI APIs, design conversation flows, and deploy your bot to the web.', curriculum: ['Chatbot Architecture','Choosing Your AI API','Setting Up the Backend','Designing Conversations','Handling User Intent','Context & Memory','Deploying to the Web','Adding Personality'] },
  { id: 8,  title: 'AI Tools Masterclass 2026',      category: 'programming',     subcategory: 'AI Tools',          emoji: '🛠️', bg: '#fce4ec', price: 2899,  originalPrice: 7499,  rating: 4.7, reviews: 2677, level: 'intermediate', duration: '9h',     lessons: 64, instructor: 'Tom Bradley',     badge: 'New',        includes: ['9 hours of video','Tool access guide','Workflow templates','Certificate'], desc: 'Master the most powerful AI tools of 2026: Claude, GPT-4, Midjourney, Runway, and more. Build powerful workflows that multiply your productivity 10x.', curriculum: ['The AI Tool Landscape','Claude & Prompting Mastery','Image Generation Deep Dive','AI Video Tools','AI Audio & Music','Automating Workflows','Building an AI Stack','Your Personal AI System'] },
  { id: 9,  title: 'JavaScript + AI Applications',   category: 'programming',     subcategory: 'JavaScript AI',     emoji: '⚡', bg: '#fff9c4', price: 2499,  originalPrice: 6299,  rating: 4.6, reviews: 1543, level: 'intermediate', duration: '8h 30m', lessons: 60, instructor: 'Nina Kowalski',   badge: null,         includes: ['8.5 hours of video','Starter projects','API integration guide','Certificate'], desc: 'Build AI-powered web applications using JavaScript and modern AI APIs. Create intelligent features like smart search, image recognition, and AI-generated content.', curriculum: ['JS Refresher','Fetch API & Async','Integrating AI APIs','Building a Smart Search','Image Recognition App','Text Analysis Tool','Voice-Powered Interface','Deploy & Ship'] },
  { id: 10, title: 'Prompt Engineering Mastery',     category: 'programming',     subcategory: 'AI APIs',           emoji: '✍️', bg: '#e8eaf6', price: 1249,  originalPrice: 3799,  rating: 4.9, reviews: 6201, level: 'beginner',     duration: '5h',     lessons: 38, instructor: 'Dr. Maya Chen',    badge: 'Bestseller', includes: ['5 hours of video','Prompt library (200+ prompts)','Cheat sheets','Certificate'], desc: 'The art and science of talking to AI. Learn how to craft perfect prompts that get you exactly what you want from any AI model — a career-changing skill.', curriculum: ['What is Prompt Engineering?','The Anatomy of a Great Prompt','Chain-of-Thought Prompting','Few-Shot Learning','Role & Context Setting','Avoiding Common Mistakes','Advanced Techniques','Building a Prompt Library'] },

  // Creative AI
  { id: 11, title: 'AI Art — From Idea to Image',    category: 'creative',        subcategory: 'AI Art',            emoji: '🎨', bg: '#f3e5f5', price: 1699,  originalPrice: 4599,  rating: 4.8, reviews: 4521, level: 'beginner',     duration: '6h',     lessons: 44, instructor: 'Luna Vásquez',    badge: 'Popular',    includes: ['6 hours of video','Style guides','100+ prompts','Certificate'], desc: 'Unleash your inner artist with AI! Learn Midjourney, DALL-E, and Stable Diffusion to create stunning artwork, illustrations, and designs from simple text descriptions.', curriculum: ['The AI Art Revolution','Your First AI Image','Understanding Style Prompts','Midjourney Masterclass','DALL-E 3 Techniques','Consistent Characters','Building a Portfolio','Selling Your AI Art'] },
  { id: 12, title: 'AI Music Composition',           category: 'creative',        subcategory: 'AI Music',          emoji: '🎵', bg: '#e0f7fa', price: 2099,  originalPrice: 5499,  rating: 4.7, reviews: 1832, level: 'beginner',     duration: '5h 30m', lessons: 40, instructor: 'Marcus Lee',      badge: 'New',        includes: ['5.5 hours of video','Stems & samples','Tool guide','Certificate'], desc: 'Create professional music with AI tools! From background music to full tracks, learn to use Suno, Udio, and other AI music platforms to produce incredible audio.', curriculum: ['AI Music Landscape','Your First AI Track','Genre & Style Control','Lyrics & Vocals','Mixing with AI','Sound Design','Music for Content','Releasing Your Music'] },
  { id: 13, title: 'AI Video Creation & Editing',    category: 'creative',        subcategory: 'AI Video',          emoji: '🎬', bg: '#fbe9e7', price: 2899,  originalPrice: 7099,  rating: 4.8, reviews: 2901, level: 'intermediate', duration: '8h',     lessons: 58, instructor: 'Sofia Rossi',     badge: 'Popular',    includes: ['8 hours of video','Project templates','Tool access guide','Certificate'], desc: 'Create stunning videos without a film crew! Master Runway, Pika, HeyGen, and Sora to produce professional-quality video content with just a text prompt.', curriculum: ['AI Video Revolution','Text-to-Video with Sora','Runway Advanced Techniques','AI Avatars with HeyGen','Pika for Short Clips','Adding AI Voiceovers','Editing with AI','Publish & Go Viral'] },
  { id: 14, title: 'AI Writing & Storytelling',      category: 'creative',        subcategory: 'AI Writing',        emoji: '📝', bg: '#e8f5e9', price: 1249,  originalPrice: 3299,  rating: 4.9, reviews: 5123, level: 'beginner',     duration: '4h',     lessons: 30, instructor: 'Claire Morrison',  badge: 'Bestseller', includes: ['4 hours of video','Writing templates','Style guide','Certificate'], desc: 'Become a better writer with AI as your creative partner. Learn to brainstorm, outline, draft, and refine any content — blogs, stories, scripts, and more.', curriculum: ['AI as Writing Partner','Brainstorming with AI','Structure & Outlining','Drafting Techniques','Editing & Refining','Writing Different Formats','Finding Your Voice','Publishing Your Work'] },

  // AI for Kids
  { id: 15, title: 'AI Adventures for Kids (Ages 7+)',   category: 'kids', subcategory: 'Scratch + AI',  emoji: '🌟', bg: '#fff9c4', price: 849,   originalPrice: 2099,  rating: 5.0, reviews: 3201, level: 'beginner',     duration: '3h',     lessons: 20, instructor: 'Ms. Rosie Taylor', badge: 'Bestseller', includes: ['3 hours of fun video','Printable activity sheets','Parent guide','Certificate'], desc: 'Your little one\'s first step into the world of AI! Through stories, games, and colorful activities, children discover how AI works in their favorite toys, apps, and gadgets.', curriculum: ['What is a Robot?','How do Computers Think?','Teaching a Computer','AI in Your Home','Smart Assistants','AI Art Fun','Making Decisions with AI','My AI Invention'] },
  { id: 16, title: 'Scratch + AI: Build Cool Games',    category: 'kids', subcategory: 'Scratch + AI',  emoji: '🕹️', bg: '#e8f5e9', price: 1249,  originalPrice: 2899,  rating: 4.9, reviews: 2341, level: 'beginner',     duration: '5h',     lessons: 36, instructor: 'Mr. Danny Park',   badge: 'Popular',    includes: ['5 hours of video','Scratch projects','Parent guide','Certificate'], desc: 'Build fun games and animations using Scratch and AI extensions! Kids aged 8-12 will create their own interactive projects while learning computational thinking.', curriculum: ['Scratch Basics','Sprites & Costumes','Making Things Move','If/Then Thinking','Adding Sounds','AI Extensions','Build a Quiz Game','Build a Space Adventure'] },
  { id: 17, title: 'Young AI Explorers (Ages 10-14)',   category: 'kids', subcategory: 'Young Coders',  emoji: '🔬', bg: '#e3f2fd', price: 1699,  originalPrice: 4199,  rating: 4.8, reviews: 1654, level: 'beginner',     duration: '6h',     lessons: 44, instructor: 'Dr. Sam Obi',      badge: 'New',        includes: ['6 hours of video','Project files','Parent dashboard','Certificate'], desc: 'A comprehensive AI course for curious tweens! Explore machine learning, computer vision, and natural language processing through hands-on projects and experiments.', curriculum: ['AI Everywhere','How Machines See','Teaching with Images','Voice Recognition','Text Classification','Sentiment Analysis','Build an AI App','Present Your Project'] },
  { id: 18, title: 'AI Games & Creative Coding',       category: 'kids', subcategory: 'AI Games',     emoji: '🎮', bg: '#fce4ec', price: 1099,  originalPrice: 2499,  rating: 4.9, reviews: 1987, level: 'beginner',     duration: '4h',     lessons: 28, instructor: 'Ms. Rosie Taylor', badge: null,         includes: ['4 hours of video','Game templates','Certificate'], desc: 'Learn to code by building awesome AI-powered games! Perfect for kids 10-15 who love gaming and want to understand the tech behind their favorite games.', curriculum: ['Games and Code','Basic Game Logic','Adding AI Enemies','Procedural Levels','Power-Ups with AI','Leaderboards','Multiplayer Basics','Launch Your Game'] },

  // Business AI
  { id: 19, title: 'AI for Marketing & Growth',       category: 'business', subcategory: 'AI Marketing',   emoji: '📣', bg: '#fff8e1', price: 2899,  originalPrice: 7499,  rating: 4.8, reviews: 3421, level: 'beginner',     duration: '8h',     lessons: 56, instructor: 'Rachel Kim',      badge: 'Popular',    includes: ['8 hours of video','Marketing templates','AI tool guide','Certificate'], desc: 'Supercharge your marketing with AI! From content creation to campaign optimization, learn to use AI tools that save you hours every week while delivering better results.', curriculum: ['AI in Marketing Today','AI Content Creation','Email Automation','Social Media AI','Ad Copywriting','SEO with AI','Analytics & Insights','Building Your AI Stack'] },
  { id: 20, title: '10x Productivity with AI',        category: 'business', subcategory: 'AI Productivity',emoji: '⚡', bg: '#e8f5e9', price: 1699,  originalPrice: 4199,  rating: 4.9, reviews: 5621, level: 'beginner',     duration: '5h',     lessons: 38, instructor: 'Tom Bradley',     badge: 'Bestseller', includes: ['5 hours of video','Workflow templates','Checklists','Certificate'], desc: 'Reclaim your time with AI productivity hacks! Learn to automate repetitive tasks, generate reports instantly, manage emails with AI, and build workflows that run themselves.', curriculum: ['Your AI Productivity Audit','AI Email Management','Meeting Summaries & Notes','Document Creation','Research Automation','Zapier + AI Workflows','Your Daily AI Routine','Productivity Metrics'] },
  { id: 21, title: 'AI Strategy for Business Leaders', category: 'business', subcategory: 'AI Strategy',    emoji: '♟️', bg: '#fce4ec', price: 4199,  originalPrice: 10999, rating: 4.7, reviews: 1298, level: 'advanced',     duration: '10h',    lessons: 70, instructor: 'Dr. James Okonkwo', badge: 'New',       includes: ['10 hours of video','Strategy frameworks','Case studies','Certificate','1-on-1 Q&A'], desc: 'Lead your organization\'s AI transformation. This executive-focused course covers AI strategy, ROI measurement, team building, ethical governance, and competitive positioning.', curriculum: ['The AI Opportunity','Assessing AI Readiness','Choosing Your AI Initiatives','Building an AI Team','Data Strategy','Change Management','Measuring ROI','AI Governance & Risk'] },
  { id: 22, title: 'Automate Your Business with AI',  category: 'business', subcategory: 'Automation',     emoji: '🔄', bg: '#e8eaf6', price: 2499,  originalPrice: 6299,  rating: 4.8, reviews: 2876, level: 'intermediate', duration: '7h',     lessons: 52, instructor: 'Nina Kowalski',   badge: 'Popular',    includes: ['7 hours of video','Zapier blueprints','Tool guide','Certificate'], desc: 'Put your business on autopilot! Learn to build automated workflows using Zapier, Make.com, and AI tools to handle customer service, invoicing, scheduling, and reporting.', curriculum: ['Automation Basics','Zapier Essentials','Make.com Power User','AI-Powered Customer Service','Invoice & Finance Automation','Social Media Scheduling','Reporting Dashboards','Your Automation Roadmap'] },

  // Advanced
  { id: 23, title: 'Deep Learning with PyTorch',      category: 'advanced', subcategory: 'Deep Learning',  emoji: '🔥', bg: '#fbe9e7', price: 4199,  originalPrice: 9999,  rating: 4.9, reviews: 3876, level: 'advanced',     duration: '15h',    lessons: 100, instructor: 'Prof. Alex Rivera', badge: 'Bestseller', includes: ['15 hours of video','GPU access guide','Research papers','Certificate','Discord community'], desc: 'Master deep learning from theory to production! Build CNNs, RNNs, Transformers, and more using PyTorch. You\'ll train real models on real datasets with full code.', curriculum: ['PyTorch Fundamentals','Tensor Operations','Building Neural Nets','CNNs for Images','RNNs for Sequences','Transformers Architecture','Transfer Learning','Production Deployment'] },
  { id: 24, title: 'Computer Vision Masterclass',     category: 'advanced', subcategory: 'Computer Vision',emoji: '👁️', bg: '#e8f5e9', price: 3799,  originalPrice: 9199,  rating: 4.8, reviews: 2143, level: 'advanced',     duration: '12h',    lessons: 84, instructor: 'Sarah Nguyen',    badge: 'Popular',    includes: ['12 hours of video','OpenCV projects','Dataset access','Certificate'], desc: 'Make computers see and understand the world! From object detection to facial recognition and video analysis, you\'ll build production-ready computer vision systems.', curriculum: ['Image Processing Basics','OpenCV Deep Dive','Feature Extraction','Object Detection with YOLO','Semantic Segmentation','Face Recognition','Video Analysis','Deploying Vision Systems'] },
  { id: 25, title: 'Natural Language Processing Pro', category: 'advanced', subcategory: 'NLP',            emoji: '🗣️', bg: '#e8eaf6', price: 3799,  originalPrice: 9199,  rating: 4.7, reviews: 1987, level: 'advanced',     duration: '13h',    lessons: 90, instructor: 'Dr. Maya Chen',    badge: null,         includes: ['13 hours of video','HuggingFace access','NLP datasets','Certificate'], desc: 'Build systems that understand human language. Master transformers, BERT, GPT architectures, and fine-tuning techniques to create powerful text classification, Q&A, and generation models.', curriculum: ['NLP Fundamentals','Tokenization & Embeddings','Classical NLP','Transformers Revolution','BERT & Fine-Tuning','Generative Models','Question Answering','Deploy an NLP API'] },
  { id: 26, title: 'MLOps: Ship AI to Production',    category: 'advanced', subcategory: 'MLOps',          emoji: '⚙️', bg: '#fff9c4', price: 3299,  originalPrice: 8399,  rating: 4.8, reviews: 1432, level: 'advanced',     duration: '11h',    lessons: 78, instructor: 'Leo Martinez',    badge: 'New',        includes: ['11 hours of video','Docker/K8s guide','CI/CD templates','Certificate'], desc: 'The missing piece in every AI engineer\'s toolkit. Learn to version models, build CI/CD pipelines, monitor production systems, and scale AI applications reliably.', curriculum: ['The MLOps Lifecycle','Version Control for ML','Data Pipelines','Model Training at Scale','Experiment Tracking','Model Registry','CI/CD for ML','Monitoring & Alerting'] },
];

const LEARNING_PATHS = [
  { title: 'Complete AI Beginner Path', icon: '🌱', desc: 'Start from zero and build a solid AI foundation in 30 days. Perfect for total beginners.', steps: '5 courses • 30–40 hours', courses: [1, 2, 6, 10, 5] },
  { title: 'AI Creator Path',           icon: '🎨', desc: 'Master AI tools for art, music, video, and writing. Create amazing content with AI.', steps: '4 courses • 20–25 hours', courses: [11, 12, 13, 14] },
  { title: 'AI Developer Path',         icon: '💻', desc: 'Build real AI apps and chatbots. Go from Python basics to production deployments.', steps: '5 courses • 45–55 hours', courses: [6, 9, 7, 8, 26] },
  { title: 'Young Genius Path',         icon: '🧒', desc: 'For kids and teens! Learn AI through games, stories, and fun projects.', steps: '4 courses • 18–22 hours', courses: [15, 16, 17, 18] },
  { title: 'Business Leader Path',      icon: '💼', desc: 'Transform your business with AI. From productivity to full AI strategy.', steps: '4 courses • 25–30 hours', courses: [20, 19, 22, 21] },
  { title: 'AI Expert Path',            icon: '🚀', desc: 'Go deep into advanced AI. Deep learning, computer vision, NLP, and MLOps.', steps: '4 courses • 50–60 hours', courses: [23, 24, 25, 26] },
];

const PROMO_CODES = {
  'AITV20': 0.20,
  'KIDS50': 0.50,
  'LEARN10': 0.10,
  'WELCOME30': 0.30,
};
